---

- name: Install supervisor_package
  ansible.builtin.pkgng:
    name: "{{ supervisor_package }}"
    state: present

- name: "Create /etc/rc.conf.d/{{ supervisor_service }}"
  ansible.builtin.template:
    src: FreeBSD.rc.conf.j2
    dest: "/etc/rc.conf.d/{{ supervisor_service }}"
    mode: "0644"
    validate: sh -n %s

- name: Enable supervisor_service
  ansible.builtin.service:
    name: "{{ supervisor_service }}"
    enabled: yes
