---

- name: Install supervisor_package
  ansible.builtin.apt:
    name: "{{ supervisor_package }}"
    policy_rc_d: 101
    state: present

- name: Enable supervisor_service
  ansible.builtin.service:
    name: "{{ supervisor_service }}"
    enabled: yes
